<script>
    window.addEventListener('checkout:init:evaluation', event => {
        hyvaCheckout.evaluation.registerValidator('validateTPayCardData', (element, component) => {
            let token = component.get('token');
            let saved = component.get('saved');
            if (!token && saved == 'new_card') {
                return false;
            }
            return true;
        })
    })
</script>
