<script>
    window.addEventListener('checkout:init:evaluation', event => {
        hyvaCheckout.evaluation.registerValidator('validateTPayMethodSelection', (element, component) => {
            let blikCode = component.get('blikCode');
            let group = component.get('group');
            if (!blikCode && group < 1) {
                return false;
            }
            return true;
        })
    })
</script>
