<?php
declare(strict_types=1);

/** @var Template $block */
/** @var TPay $magewire */
/** @var Escaper $escaper */

$issuers = $magewire->getIssuers();

use Snowdog\Hyva\Checkout\TPay\Payment\Method\TPay;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<div class="col-span-6" wire:payment-method="tpaycom_magento2basic">
    <div class="tpay-insidebg">
        <div class="blik">
            <div class="tpay-header-wrapper">
                <div class="tpay-header-logo">
                    <img class="tpay-logo" src="https://tpay.com/img/banners/tpay_logo_white.svg"/>
                </div>
                <div class="tpay-header-belt"></div>
            </div>
            <div class="tpay-panel-inside-content">
                <div class="tpay-channel-form-wrapper tpay-content-wrapper-class">
                    <img src="https://secure.tpay.com/_/banks/b64.png"/>
                    <div class="tpay-row">
                        <p>
                            Type in 6 digit code and press pay to commit blik payment.
                        </p>
                        <div class="tpay-input-blik-code">
                            <div class="tpay-input-wrapper">
                                <div class="tpay-input-label">
                                    BLIK code
                                </div>
                                <input id="blik_code"
                                       name="blik_code"
                                       pattern="\d*"
                                       type="tel"
                                       autocomplete="off"
                                       maxlength="6"
                                       minlength="6"
                                       placeholder="000000"
                                       tabindex="1"
                                       value=""
                                       class="tpay-input-value tpay-blik-input"
                                       wire:model="blikCode"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="tpay-basic-main-payment">
            <div class="tpay-header-wrapper">
                <div class="tpay-header-logo">
                    <img class="tpay-logo" src="https://tpay.com/img/banners/tpay_logo_white.svg"/>
                </div>
                <div class="tpay-header-belt"></div>
            </div>
            <p>Choose a payment method</p>
            <div id="groups_v" class="tpay-panel-inside-content">
                <div id="bank-selection-form" class="tpay-groups-wrapper">
                </div>
            </div>
            <input type="hidden" id="tpay-channel-input" name="tpay-channel-input"/>
        </div>
    </div>
    <span><?= $magewire->addCss() ?></span>

    <div class="checkout-agreements-block">

        <div class="TpayRegulations">
            <input type="checkbox" checked name="accept_tos" id="accept_tos" wire:model="acceptTos"/>
            <label for="accept_tos">
                <a target="_blank" href="<?= $magewire->getTerms() ?>">I do accept tpay.com service regulations</a>.
            </label>
        </div>
    </div>

</div>