<?php
declare(strict_types=1);

/** @var Template $block */
/** @var TPayGeneric $magewire */
/** @var Escaper $escaper */

use Snowdog\Hyva\Checkout\TPay\Payment\Method\TPayGeneric;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<div>
    <div class="checkout-agreements-block">
        <div class="TpayRegulations tpay-regulations-offset">
            <input
                    class="cursor-pointer"
                    type="checkbox"
                    checked
                    name="accept_tos"
                    id="accept_tos"
            />
            <label for="accept_tos">
                <span><?= $escaper->escapeHtml(__('By paying, you accept ')) ?></span>
                <a target="_blank" href="<?= $escaper->escapeUrl($magewire->getTerms()) ?>"><?= $escaper->escapeHtml(__('regulations')) ?></a>.<br>
                <span>
                        <?= $escaper->escapeHtml(__(
                                                     'The personal data administrator is Krajowy Integrator Płatności S.A with its registered office in Poznań. '
                                                 ))
                        ?>
                    </span><br>
                <a target="_blank" href="<?= $escaper->escapeUrl($magewire->getRegulations()) ?>"><?= $escaper->escapeHtml(__('Show full content')) ?></a>.
            </label>
        </div>
    </div>
</div>
